"""add unique constraint to budgets

Revision ID: 032d556f3e53
Revises: ff0721794a82
Create Date: 2026-03-21 22:10:40.793041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032d556f3e53'
down_revision: Union[str, Sequence[str], None] = 'ff0721794a82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_budget_user_month_category', 'budgets', ['user_id', 'year_month', 'category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_budget_user_month_category', 'budgets', type_='unique')
    # ### end Alembic commands ###
