"""add_milestone_flags_to_goals

Revision ID: 11f31d77710f
Revises: 3912d4fcce75
Create Date: 2026-05-28 12:36:34.869630

"""
"""add_milestone_flags_to_goals

Revision ID: 11f31d77710f
Revises: 3912d4fcce75
Create Date: 2026-05-28 12:36:34.869630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f31d77710f'
down_revision: Union[str, Sequence[str], None] = '3912d4fcce75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('is_25_notified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('goals', sa.Column('is_50_notified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('goals', sa.Column('is_75_notified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'is_75_notified')
    op.drop_column('goals', 'is_50_notified')
    op.drop_column('goals', 'is_25_notified')
    # ### end Alembic commands ###
