"""add_notifications_table_and_budget_notification_flags

Revision ID: 4ef15ef76444
Revises: 032d556f3e53
Create Date: 2026-04-28 11:52:07.622562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef15ef76444'
down_revision: Union[str, Sequence[str], None] = '032d556f3e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('budgets', sa.Column('is_warning_notified', sa.Boolean(), nullable=False))
    op.add_column('budgets', sa.Column('is_exceeded_notified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'is_exceeded_notified')
    op.drop_column('budgets', 'is_warning_notified')
    op.drop_table('notifications')
    # ### end Alembic commands ###
